3.1.0
Adds type (Mono) for TCP SHARK APPEARANCE instead of abolishing -C option.

diff --git a/tcpshark b/tcpshark
--- a/tcpshark
+++ b/tcpshark
@@ -2,7 +2,7 @@
 ##################### DONT EDIT THIS FILE ######################
 #                                                              #
 NAME="tcpshark - Packet analyzer for TCP troubleshooting"      #
-VERSION="3.0.3"                                                #
+VERSION="3.1.0"                                                #
 AUTHOR="Hirose, Manabu <manabapp@gmail.com>"                   #
 #                                                              #
 #                            Copyright (C) 2014-2022 manabapp. #
@@ -15,7 +15,7 @@ MAX_STREAMS_DEFAULT=262144
 MAX_STREAMS_LIMIT=1048576
 MAX_INFOLEN_DEFAULT=48
 MAX_LENGTH_LIMIT=65536
-APPEARANCE_DEFAULT=1   # Dark
+APPEARANCE_DEFAULT=0   # Mono
 
 #==============================================================#
 # Function: Prints usage                                       #
@@ -23,12 +23,12 @@ APPEARANCE_DEFAULT=1   # Dark
 usage()
 {
 if [ $OS_TYPE -eq 0 ]; then
-    echo "usage: tcpshark -r <infile> [-H] [-C] [-t a|ad|r] [-p <port>] [-4 | -6 | -a <addr>] [-d] [-z | -f <field>]" 1>&2
+    echo "usage: tcpshark -r <infile> [-H] [-t a|ad|r] [-p <port>] [-4 | -6 | -a <addr>] [-d] [-z | -f <field>]" 1>&2
 else
-    echo "usage: tcpshark -r <infile> [-H] [-C] [-t a|ad|r] [-p <port>] [-4 | -6 | -a <addr>] [-z | -f <field>]" 1>&2
+    echo "usage: tcpshark -r <infile> [-H] [-t a|ad|r] [-p <port>] [-4 | -6 | -a <addr>] [-z | -f <field>]" 1>&2
 fi
-    echo "       tcpshark -r <infile> -s <index> [-H] [-C] [-t a|ad|dd|e|r|rs] [-v] [-w] [-q] [-z] [-o | -x <length> | -f <field>]" 1>&2
-    echo "       tcpshark -r <infile> -n <number> [-C]" 1>&2
+    echo "       tcpshark -r <infile> -s <index> [-H] [-t a|ad|dd|e|r|rs] [-v] [-w] [-q] [-z] [-o | -x <length> | -f <field>]" 1>&2
+    echo "       tcpshark -r <infile> -n <number>" 1>&2
     echo "       tcpshark -h  (TcpShark's Manual)" 1>&2
     exit 1
 }
@@ -65,7 +65,7 @@ print_help()
     echo ""
     echo "SYNOPSIS"
     echo "    <list mode>"
-    echo "    tcpshark -r <infile> [-H] [-C] [-t a|ad|r] [-p <port>] [-4 | -6 | -a <addr>]"
+    echo "    tcpshark -r <infile> [-H] [-t a|ad|r] [-p <port>] [-4 | -6 | -a <addr>]"
 if [ $OS_TYPE -eq 0 ]; then
     echo "                         [-d] [-z | -f <field>]"
 else
@@ -73,11 +73,11 @@ else
 fi
     echo ""
     echo "    <flow mode>"
-    echo "    tcpshark -r <infile> -s <index> [-H] [-C] [-t a|ad|dd|e|r|rs] [-v] [-w] [-q]"
+    echo "    tcpshark -r <infile> -s <index> [-H] [-t a|ad|dd|e|r|rs] [-v] [-w] [-q]"
     echo "                         [-z] [-o | -x <length> | -f <field>]"
     echo ""
     echo "    <one mode>"
-    echo "    tcpshark -r <infile> -n <number> [-C]"
+    echo "    tcpshark -r <infile> -n <number>"
     echo ""
     echo "DESCRIPTION"
     echo "    TcpShark is network analyzing script, powered by Wireshark."
@@ -105,10 +105,6 @@ fi
     echo ""
     echo "    -H"
     echo "          Omits the header information."
-    echo ""
-    echo "    -C"
-    echo "          Displays a result in colorless."
-    echo "          In default, displays colorfully with ANSI color escape sequences."
     echo ""
     echo "    -t a|ad|dd|e|r|rs"
     echo "          Selects the format of the packet timestamp."
@@ -357,8 +353,9 @@ fi
     echo ""
     echo "    TCPSHARK_APPEARANCE"
     echo "          TcpShark displays colorfully with ANSI color escape sequences."
-    echo "          Selects appearance according to your terminal color from 'Dark' or"
-    echo "          'Light'. Default is 'Dark'."
+    echo "          Selects appearance according to your terminal color from 'Dark'"
+    echo "          'Light' or 'Mono'. 'Dark' is recommended."
+    echo "          If 'Mono(default)', displays in monochrome."
     echo "          If your terminal's background is whitish color, set 'Light'."
     echo ""
     echo "    TCPSHARK_MAX_INFORMATION_LENGTH"
@@ -2211,10 +2208,9 @@ AWK_COMMAND="awk"
 GREP_COMMAND="grep"
 MAX_STREAMS=$MAX_STREAMS_DEFAULT
 MAX_INFOLEN=$MAX_INFOLEN_DEFAULT
-APPEARANCE=$APPEARANCE_DEFAULT   # 0:Colorless, 1:Dark(default), 2:Light
+APPEARANCE=$APPEARANCE_DEFAULT   # 0:Colorless, 1:Dark, 2:Light
 
 FLAG_H=0
-FLAG_C=0
 FLAG_4=0
 FLAG_6=0
 FLAG_D=0
@@ -2246,16 +2242,6 @@ FILTER_PORT=0
 FILTER_ADDR=""
 STREAM_INDEX=0
 FRAME_NUMBER=0
-
-ACES_BOLD=""
-ACES_RED=""
-ACES_GREEN=""
-ACES_YELLOW=""
-ACES_BLUE=""
-ACES_MAGENTA=""
-ACES_CYAN=""
-ACES_GRAY=""
-ACES_END=""
 
 #==============================================================#
 # Checks OS type                                               #
@@ -2298,13 +2284,66 @@ case $platform in
 esac
 
 #==============================================================#
+# Sets ANSI color escape sequences                             #
+#==============================================================#
+if [ -n "$TCPSHARK_APPEARANCE" ]; then
+    case $TCPSHARK_APPEARANCE in
+        mono|Mono|MONO)
+            APPEARANCE=0
+            ;;
+        dark|Dark|DARK)
+            APPEARANCE=1
+            ;;
+        light|Light|Light)
+            APPEARANCE=2
+            ;;
+        *)
+            printf "WARNING: Invalid enviroment variable (TCPSHARK_APPEARANCE).\n" 1>&2
+            exit 1
+            ;;
+    esac
+fi
+ACES_BOLD=""
+ACES_RED=""
+ACES_GREEN=""
+ACES_YELLOW=""
+ACES_BLUE=""
+ACES_MAGENTA=""
+ACES_CYAN=""
+ACES_GRAY=""
+ACES_END=""
+case $APPEARANCE in
+    1)
+        ACES_BOLD="\033[1;97m"
+        ACES_RED="\033[1;91m"
+        ACES_GREEN="\033[1;92m"
+        ACES_YELLOW="\033[1;93m"
+        ACES_BLUE="\033[1;94m"
+        ACES_MAGENTA="\033[1;95m"
+        ACES_CYAN="\033[1;96m"
+        ACES_GRAY="\033[37m"
+        ACES_END="\033[0m"
+        ;;
+    2)
+        ACES_BOLD="\033[1;30m"
+        ACES_RED="\033[1;31m"
+        ACES_GREEN="\033[1;32m"
+        ACES_YELLOW="\033[1;33m"
+        ACES_BLUE="\033[1;34m"
+        ACES_MAGENTA="\033[1;35m"
+        ACES_CYAN="\033[1;36m"
+        ACES_GRAY="\033[90m"
+        ACES_END="\033[0m"
+        ;;
+esac
+
+#==============================================================#
 # Gets options                                                 #
 #==============================================================#
-while getopts "HC46dvwqzohVr:s:n:t:p:a:x:f:" flag; do
+while getopts "H46dvwqzohVr:s:n:t:p:a:x:f:" flag; do
     case $flag in
         \?) usage;;
         H) FLAG_H=1;;
-        C) FLAG_C=1; APPEARANCE=0;;
         4) FLAG_4=1;;
         6) FLAG_6=1;;
         d) FLAG_D=1;;
@@ -2456,21 +2495,6 @@ if [ -n "$TCPSHARK_MAX_STREAMS" ]; then
     MAX_STREAMS=$TCPSHARK_MAX_STREAMS
 fi
 
-if [ -n "$TCPSHARK_APPEARANCE" -a $FLAG_C -eq 0 ]; then
-    case $TCPSHARK_APPEARANCE in
-        dark|Dark|DARK)
-            APPEARANCE=1
-            ;;
-        light|Light|Light)
-            APPEARANCE=2
-            ;;
-        *)
-            printf "ERROR: Invalid enviroment variable (TCPSHARK_APPEARANCE).\n" 1>&2
-            exit 1
-            ;;
-    esac
-fi
-
 if [ -n "$TCPSHARK_MAX_INFORMATION_LENGTH" ]; then
     check_length $TCPSHARK_MAX_INFORMATION_LENGTH
     if [ $? -ne 0 ]; then
@@ -2479,34 +2503,6 @@ if [ -n "$TCPSHARK_MAX_INFORMATION_LENGTH" ]; then
     fi
     MAX_INFOLEN=$TCPSHARK_MAX_INFORMATION_LENGTH
 fi
-
-#==============================================================#
-# Sets ANSI color escape sequences                             #
-#==============================================================#
-case $APPEARANCE in
-    1)
-        ACES_BOLD="\033[1;97m"
-        ACES_RED="\033[1;91m"
-        ACES_GREEN="\033[1;92m"
-        ACES_YELLOW="\033[1;93m"
-        ACES_BLUE="\033[1;94m"
-        ACES_MAGENTA="\033[1;95m"
-        ACES_CYAN="\033[1;96m"
-        ACES_GRAY="\033[37m"
-        ACES_END="\033[0m"
-        ;;
-    2)
-        ACES_BOLD="\033[1;30m"
-        ACES_RED="\033[1;31m"
-        ACES_GREEN="\033[1;32m"
-        ACES_YELLOW="\033[1;33m"
-        ACES_BLUE="\033[1;34m"
-        ACES_MAGENTA="\033[1;35m"
-        ACES_CYAN="\033[1;36m"
-        ACES_GRAY="\033[90m"
-        ACES_END="\033[0m"
-        ;;
-esac
 
 #==============================================================#
 # Checks wireshark version                                     #
