Add files via upload

diff --git a/tcpshark_dev b/tcpshark_dev
--- a/tcpshark_dev
+++ b/tcpshark_dev
@@ -102,9 +102,6 @@ fi
     echo ""
     echo "    -n <number>"
     echo "          Displays the specific packet in one mode."
-    echo "          In this mode, output of the following command is displayed as is."
-    echo ""
-    echo "            $ tshark -r <infile> -Y \"frame.number == <number>\" -V"
     echo ""
     echo "    -H"
     echo "          Omits the header information."
@@ -186,111 +183,119 @@ fi
     echo "          Prints the version and exits."
     echo ""
     echo "OUTPUT FORMAT"
+    echo "    In each mode, streams or packets are output in the following format:"
     echo ""
-    echo "  <list mode>"
+    echo "    <list mode>"
+    echo "      Index              Stream index."
     echo ""
-    echo "    Index              Stream index."
+    echo "      TIME               Timestamp in first packet."
     echo ""
-    echo "    TIME               Timestamp in first packet."
+    echo "      Src/Dst ADDRESS    Source/Destination IP address and port."
+    echo "                         When IPv6 packets are encapsulated into IPv4 (6to4,"
+    echo "                         6in4, or 6rd), both address pairs of the stream are"
+    echo "                         displayed."
     echo ""
-    echo "    Src/Dst ADDRESS    Source/Destination IP address and port."
-    echo "                       When IPv6 packets are encapsulated into IPv4 (6to4, 6in4,"
-    echo "                       or 6rd), both address pairs of the stream are displayed."
+    echo "      Duration           Period between first/last packets."
     echo ""
-    echo "    Duration           Period between first/last packets."
+    echo "      FLAGS              TCP flag's bitwize OR on all packets."
     echo ""
-    echo "    FLAGS              TCP flag's bitwize OR on all packets."
+    echo "                           F : Fin"
+    echo "                           S : Syn"
+    echo "                           R : Reset"
+    echo "                           P : Push"
+    echo "                           A : Acknowledgment"
+    echo "                           U : Urgent"
+    echo "                           E : ECN-Echo"
+    echo "                           C : Congestion Window Reduced (CWR)"
+    echo "                           N : Nonce"
     echo ""
-    echo "                         F : Fin"
-    echo "                         S : Syn"
-    echo "                         R : Reset"
-    echo "                         P : Push"
-    echo "                         A : Acknowledgment"
-    echo "                         U : Urgent"
-    echo "                         E : ECN-Echo"
-    echo "                         C : Congestion Window Reduced (CWR)"
-    echo "                         N : Nonce"
+    echo "      Packets Bytes      Number of packets count and total of TCP data length in"
+    echo "                         each direction."
+    echo "                         Note that data length is not a frame size."
     echo ""
-    echo "    Packets Bytes      Number of packets count and total of TCP data length in"
-    echo "                       each direction."
-    echo "                       Note that data length is not a frame size."
+    echo "      Custom STATISTICS  Number of packets which includes the specified field."
+    echo "                         Calculates sum-total, minimum, maximum and average"
+    echo "                         value, if field type is numerical (INT, UINT, BOOLEAN,"
+    echo "                         DOUBLE, FLOAT, or RELATIVE_TIME)."
     echo ""
-    echo "    Custom STATISTICS  Number of packets which includes the specified field."
-    echo "                       Calculates sum-total, minimum, maximum and average value,"
-    echo "                       if field type is numerical (INT, UINT, BOOLEAN, DOUBLE,"
-    echo "                       FLOAT, or RELATIVE_TIME)."
+    echo "      Analysis           TCP analysis statistics."
     echo ""
-    echo "    Analysis           TCP analysis statistics."
+    echo "                           ret : Retransmission"
+    echo "                           fst : Fast Retransmission"
+    echo "                           spu : Spurious Retransmission  (Wireshark 1.12.0 or newer)"
+    echo "                           dup : Duplicate ACK"
+    echo "                           out : Out Of Order"
+    echo "                           los : Previous Segment Unseen"
+    echo "                           alo : ACKed Unseen Packet"
+    echo "                           wup : Window update"
+    echo "                           ful : Window full"
+    echo "                           zro : Zero Window"
+    echo "                           zrp : Zero Window Probe"
+    echo "                           zpa : Zero Window Probe Ack"
+    echo "                           kep : Keep Alive"
+    echo "                           kpa : Keep Alive ACK"
+    echo "                           tfo : SYN with TFO cookie      (Wireshark 2.0.0 or newer)"
+    echo "                           afo : Accepting TFO data       (Wireshark 3.4.0 or newer)"
+    echo "                           ifo : Ignoring TFO data        (Wireshark 3.4.0 or newer)"
+    echo "                           prt : TCP Port numbers reused"
     echo ""
-    echo "                         ret : Retransmission"
-    echo "                         fst : Fast Retransmission"
-    echo "                         spu : Spurious Retransmission  (Wireshark 1.12.0 or newer)"
-    echo "                         dup : Duplicate ACK"
-    echo "                         out : Out Of Order"
-    echo "                         los : Previous Segment Unseen"
-    echo "                         alo : ACKed Unseen Packet"
-    echo "                         wup : Window update"
-    echo "                         ful : Window full"
-    echo "                         zro : Zero Window"
-    echo "                         zrp : Zero Window Probe"
-    echo "                         zpa : Zero Window Probe Ack"
-    echo "                         kep : Keep Alive"
-    echo "                         kpa : Keep Alive ACK"
-    echo "                         tfo : SYN with TFO cookie      (Wireshark 2.0.0 or newer)"
-    echo "                         afo : Accepting TFO data       (Wireshark 3.4.0 or newer)"
-    echo "                         ifo : Ignoring TFO data        (Wireshark 3.4.0 or newer)"
-    echo "                         prt : TCP Port numbers reused"
+    echo "    <flow mode>"
+    echo "      No.                Packet number in capture file."
     echo ""
-    echo "  <flow mode>"
+    echo "      TIME               Timestamp in each packet."
     echo ""
-    echo "    No.                Packet number in capture file."
+    echo "      WINDOW Size        TCP windows size."
     echo ""
-    echo "    TIME               Timestamp in each packet."
+    echo "      Src/Dst PORT       Source or Destination port."
     echo ""
-    echo "    WINDOW Size        TCP windows size."
+    echo "      LENGTH             TCP segment length."
     echo ""
-    echo "    Src/Dst PORT       Source or Destination port."
-    echo ""
-    echo "    LENGTH             TCP segment length."
-    echo ""
-    echo "    FLAGS              TCP flags."
+    echo "      FLAGS              TCP flags."
     echo "                       Please refer to the description in <list mode>."
     echo ""
-    echo "    SEQ/ACK Number     Sequence or Acknowledgment number."
+    echo "      SEQ/ACK Number     Sequence or Acknowledgment number."
     echo ""
-    echo "    OPTION             TCP options."
+    echo "      OPTION             TCP options."
     echo ""
-    echo "                         mwSstO"
-    echo "                         ------"
-    echo "                         |||||+ Other option (except EOL, NOP)"
-    echo "                         ||||+- TCP Time Stamp Option"
-    echo "                         |||+-- TCP SACK Option"
-    echo "                         ||+--- TCP SACK Permitted Option"
-    echo "                         |+---- TCP Window Scale Option"
-    echo "                         +----- TCP MSS Option"
+    echo "                           mwSstO"
+    echo "                           ------"
+    echo "                           |||||+ Other option (except EOL, NOP)"
+    echo "                           ||||+- TCP Time Stamp Option"
+    echo "                           |||+-- TCP SACK Option"
+    echo "                           ||+--- TCP SACK Permitted Option"
+    echo "                           |+---- TCP Window Scale Option"
+    echo "                           +----- TCP MSS Option"
     echo ""
-    echo "    Analysis           TCP analysis information for TCP troubleshooting."
-    echo "                       Please refer to the description in <list mode>."
+    echo "      Analysis           TCP analysis information for TCP troubleshooting."
+    echo "                         Please refer to the description in <list mode>."
     echo ""
-    echo "    Option VALUES      TCP Option's values (if some bits in OPTION area are set)."
+    echo "      Option VALUES      TCP Option's values (if some bits in OPTION area are"
+    echo "                         set)."
     echo ""
-    echo "                         [m] MSS=XXX             : MSS value"
-    echo "                         [w] WS=XXX(YYY)         : Shift count, multiplier"
-    echo "                         [S] SACK_PERM=1         : ---"
-    echo "                         [s] SLE=XXX SRE=YYY     : TCP ACK left edge, right edge"
-    echo "                         [t] TSval=XXX TSecr=YYY : Timestamp value, echo reply"
-    echo "                         [O] OTHER(kind:XXX)     : TCP option's kind"
+    echo "                           [m] MSS=XXX             : MSS value"
+    echo "                           [w] WS=XXX(YYY)         : Shift count, multiplier"
+    echo "                           [S] SACK_PERM=1         : ---"
+    echo "                           [s] SLE=XXX SRE=YYY     : TCP ACK left edge, right edge"
+    echo "                           [t] TSval=XXX TSecr=YYY : Timestamp value, echo reply"
+    echo "                           [O] OTHER(kind:XXX)     : TCP option's kind"
     echo ""
-    echo "    Payload DATA       Hexadecimal dump and printable ascii string of TCP"
-    echo "                       segment data."
+    echo "      Payload DATA       Hexadecimal dump and printable ascii string of TCP"
+    echo "                         segment data."
     echo ""
-    echo "    Custom VALUE       Value of specified custom field."
-    echo "                       Only displays if each packet includes the field."
+    echo "      Custom VALUE       Value of specified custom field."
+    echo "                         Only displays if each packet includes the field."
     echo ""
-    echo "    Expert INFO        TCP expert information."
-    echo "                       Additional information according to the specified type is"
-    echo "                       displayed."
+    echo "      Expert INFO        TCP expert information."
+    echo "                         Additional information according to the specified type"
+    echo "                         is displayed."
     echo ""
+    echo "    <one mode>"
+    echo "      Output of the following command is displayed as is."
+    echo ""
+    echo "        $ tshark -r <infile> -Y \"frame.number == <number>\" -V"
+    echo ""
+    echo ""
+    echo "ENVIRONMENT VARIABLES"
     echo "    TCPSHARK_TSHARK_COMMAND"
     echo "          File path of executable command 'tshark'."
     echo "          If the command is not found on your lab, set the full path of tshark."
@@ -1760,7 +1765,7 @@ tcp_stream_flow()
             else if (cnt == 2) printf(" "); 
         }
         if (hexdump) {
-            #printf(e_payload)
+            gsub(":", "", e_payload)  # for wireshark 2.x
             dump_data(e_payload)
         }
         else if (custom) {
@@ -2359,6 +2364,17 @@ case "$version" in
     [4-9].*)        ANALYSIS_LEVEL=3;;
     *)              printf "ERROR: Wireshark's version too old.\n" 1>&2; exit 1;;
 esac
+
+#==============================================================#
+# Checks custom filed                                          #
+#==============================================================#
+if [ $FLAG_X -eq 1 ]; then
+    $TSHARK_COMMAND -G fields | grep "\ttcp.payload\t" > /dev/null
+    if [ $? -ne 0 ]; then
+        printf "ERROR: -x option not supported because your wireshark version is old.\n" 1>&2
+        exit 1
+    fi
+fi
 
 #==============================================================#
 # Checks custom filed                                          #
