Add files via upload

diff --git a/tcpshark b/tcpshark
--- a/tcpshark
+++ b/tcpshark
@@ -2,7 +2,7 @@
 ######################## DONT EDIT THIS FILE #########################
 #                                                                    #
 NAME="tcpshark - Packet analyzer for TCP troubleshooting"            #
-VERSION="0.9v"                                                       #
+VERSION="0.9w"                                                       #
 AUTHOR="Hirose, Manabu <manabapp@gmail.com>"                         #
 #                                                                    #
 #                                       Copyright (C) 2021 manabapp. #
@@ -301,24 +301,6 @@ check_number()
     return 1
 }
 
-check_ipv4()
-{
-    echo "$1" | grep -E '^((25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\.){3}(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])$' > /dev/null
-    if [ $? -eq 0 ] ; then
-        return 0
-    fi
-    return 1
-}
-
-check_ipv6()
-{
-    echo "$1" | grep -E '(([0-9a-fA-F]{1,4}:){7,7}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,7}:|([0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,5}(:[0-9a-fA-F]{1,4}){1,2}|([0-9a-fA-F]{1,4}:){1,4}(:[0-9a-fA-F]{1,4}){1,3}|([0-9a-fA-F]{1,4}:){1,3}(:[0-9a-fA-F]{1,4}){1,4}|([0-9a-fA-F]{1,4}:){1,2}(:[0-9a-fA-F]{1,4}){1,5}|[0-9a-fA-F]{1,4}:((:[0-9a-fA-F]{1,4}){1,6})|:((:[0-9a-fA-F]{1,4}){1,7}|:)|fe80:(:[0-9a-fA-F]{0,4}){0,4}%[0-9a-zA-Z]{1,}|::(ffff(:0{1,4}){0,1}:){0,1}((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])|([0-9a-fA-F]{1,4}:){1,4}:((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9]))' > /dev/null
-    if [ $? -eq 0 ] ; then
-        return 0
-    fi
-    return 1
-}
-
 check_ftype()
 {
     $TSHARK_COMMAND -G fields | $AWK_COMMAND -F "\t" -v field="$1" '
@@ -411,8 +393,10 @@ tcp_stream_list()
     #==============================================#
     # Builds tshark's filter                       #
     #==============================================#
+    nofilter=1
     if [ $FLAG_P -eq 1 ]; then
         tshark_filter="tcp.port == $FILTER_PORT"
+        nofilter=0
     fi
     if [ $FLAG_A -eq 1 ]; then
         echo "$FILTER_ADDR" | grep : > /dev/null
@@ -421,12 +405,29 @@ tcp_stream_list()
         else
             tshark_filter="$tshark_filter and ip.addr == $FILTER_ADDR"
         fi
+        nofilter=0
     fi
     if [ $FLAG_4 -eq 1 ]; then
         tshark_filter="$tshark_filter and ip"
+        nofilter=0
     fi
     if [ $FLAG_6 -eq 1 ]; then
         tshark_filter="$tshark_filter and ipv6"
+        nofilter=0
+    fi
+    
+    #==============================================#
+    # Finds specific stream                             #
+    #==============================================#
+    if [ $nofilter -eq 0 ]; then
+        line=`$TSHARK_COMMAND -r $TSHARK_INFILE -R "$tshark_filter" -2 -c 1`
+        if [ $? -ne 0 ]; then
+            return 1
+        fi
+        if [ -z "$line" ]; then
+            printf "WARNING: No such TCP stream.\n" 1>&2
+            return 1
+        fi
     fi
     
     #==============================================#
@@ -1725,6 +1726,12 @@ if [ $FLAG_S -eq 0 ]; then
     if [ $FLAG_4 -eq 1 -a $FLAG_6 -eq 1 ]; then
         usage
     fi
+    if [ $FLAG_4 -eq 1 -a $FLAG_A -eq 1 ]; then
+        usage
+    fi
+    if [ $FLAG_6 -eq 1 -a $FLAG_A -eq 1 ]; then
+        usage
+    fi
     if [ $FLAG_X -eq 1 -a $FLAG_F -eq 1 ]; then
         usage
     fi
@@ -1744,23 +1751,6 @@ if [ $FLAG_S -eq 1 ]; then
     if [ $? -ne 0 ]; then
         printf "ERROR: Invalid stream index.\n" 1>&2
         exit 1
-    fi
-fi
-
-if [ $FLAG_A -eq 1 ]; then
-    echo "$FILTER_ADDR" | grep : > /dev/null
-    if [ $? -eq 0 ]; then
-        check_ipv6 "$FILTER_ADDR"
-        if [ $? -ne 0 ]; then
-            printf "ERROR: Invalid IPv6 format.\n" 1>&2
-            exit 1
-        fi
-    else
-        check_ipv4 "$FILTER_ADDR"
-        if [ $? -ne 0 ]; then
-            printf "ERROR: Invalid IPv4 format.\n" 1>&2
-            exit 1
-        fi
     fi
 fi
 
@@ -1925,7 +1915,7 @@ if [ $FLAG_F -eq 1 ]; then
     check_ftype $CUSTOM_FIELD
     CUSTOM_FTYPE=$?
     if [ $CUSTOM_FTYPE -eq 0 ]; then
-        printf "ERROR: Field not supported ($CUSTOM_FIELD)." 1>&2
+        printf "ERROR: Field not supported ($CUSTOM_FIELD).\n" 1>&2
         exit 1
     fi
 fi
